# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flat

import flatbuffers

# /// A normal human player
class HumanPlayer(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsHumanPlayer(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HumanPlayer()
        x.Init(buf, n + offset)
        return x

    # HumanPlayer
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def HumanPlayerStart(builder): builder.StartObject(0)
def HumanPlayerEnd(builder): return builder.EndObject()
